matrix:
  include:
    - os: linux
      language: generic
      node_js: "10"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libusb-1.0-0-dev
      - libudev-dev

install:
  - echo "Installing node modules."
  - npm install

script:
  - echo "Building app and running tests."
  - npm test

  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "Packaging and distributing build."
      npm run build:linux
    else
      echo "Skipping packaging and distribution."
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

notifications:
  email:
    on_success: never
